### ISSUE TITLE
Make the client class configurable

### ISSUE THREAD

**Issue by gergelypolonkai** [shmup/miniboa#13]
While writing a telnet-enabled service, I created a lot of helper functions that are related to the clients.  Obviously, I soon created a whole class to include these functions, but keeping a list with all the `Client` objects is a bit cumbersome.

I had an idea in mind to subclass `TelnetClient`, and add all the methods there, but there is no way to pass this class to `TelnetServer`. I already made a patch locally to make this possible, are you interested in such a change?

**Comment by shmup** [comment]
I am. If your implementation is in a state you're happy with, I'll look it over via a PR.

**Comment by gergelypolonkai** [comment]
Sorry for the late response, my newborn son made the delay :)

I have opened #14 for this.

**Comment by shmup** [comment]
Congratulations on your new son, by the way. 😃 @gergelypolonkai
