### ISSUE TITLE
Release change with `client_class`???

### ISSUE THREAD

**Issue by harlowja** [shmup/miniboa#17]
I thought this was released, but apparently not :(

```
$ pip freeze | grep miniboa
miniboa==1.0.2
```

```
TypeError: __init__() got an unexpected keyword argument 'client_class'
```

Anyway we can get a release 1.0.3 :)

**Comment by shmup** [comment]
Woops! Yes, let me take care of this. :)

**Comment by harlowja** [comment]
Thanks!

**Comment by shmup** [comment]
Should be good to go:

https://pypi.python.org/pypi/miniboa

**Comment by harlowja** [comment]
Much appreciated :)
