### ISSUE TITLE
Async is a reserved word in Python 3.7

### ISSUE THREAD

**Issue by Tizen** [shmup/miniboa#23]
When trying to use TelnetServer on Python 3.7 the following error occurs:

```
SyntaxError: invalid syntax
>>> from .async import TelnetServer
  File "<stdin>", line 1
    from .async import TelnetServer
```

The cause of this is due to async becoming a reserved word in the latest version of Python.

I was able to fix this issue locally by renaming async.py to something else and updating the reference to it in \_\_init\_\_.py

**Comment by shmup** [comment]
hey @Tizen I just now saw this, or so I think? I should address this!

**Comment by Tizen** [comment]
Hi sorry, I closed this because I fixed the issue myself with PR#25 https://github.com/shmup/miniboa/pull/25

**Comment by hroncok** [comment]
Thanks for the fix. Could you please release the fixed version on PyPI?

**Comment by michael-lazar** [comment]
For those looking for a temporary work-around, you can install directly from the master branch

```
pip install git+https://github.com/shmup/miniboa.git@master --upgrade
```

**Comment by shmup** [comment]
I will get that on pypi today @hroncok !

Thanks for reminding me :)

**Comment by shmup** [comment]
I just cut the release and all tests are passing

Thanks everyone

cc: @hroncok
