### ISSUE TITLE
Python 3.x compatabilty

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shmup/miniboa#6]
```
What steps will reproduce the problem?
1. Attempt to run miniboa with Python 3.x
2.
3.

What is the expected output? What do you see instead? The system is expected to 
start. I get invalid syntax errors.


What version of the product are you using? On what operating system?
Miniboa r42, Python 3.1, Windows 7

Please provide any additional information below.
Python 3.1 requires that all print statements are enclosed in parenthesis.

```

Original issue reported on code.google.com by `spacedo...@gmail.com` on 9 Aug 2010 at 1:41

**Comment by shmup** [comment]
This is fixed in https://github.com/shmup/miniboa/commit/13e4a08a10346922ec30555c5bb6574a11814eeb

Backwards compatibility with Python 2 is now implemented, also: https://github.com/shmup/miniboa/commit/f405ae76d0caea72afc41e6d54f4fb7b6570654a
